version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.1.0
jobs:
  build:
    docker:
      - image: circleci/node:12.10
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - checkout
      - restore_cache:
          key: rsp-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Write npmrc
          command: |
            if [ $NPM_PASSWORD ]; then
              cp .circleci/.npmrc .npmrc
            fi

      - run:
          name: build
          command: |
            if [ $NPM_PASSWORD ]; then
              make adobe_setup
            fi
            yarn --pure-lockfile

      - save_cache:
         paths:
           - node_modules
         key: rsp-yarn-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - ~/react-spectrum
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

  test:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: test
          command: make ci-test

  lint:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: lint
          command: make lint

  storybook:
    docker:
      - image: circleci/node:12.10
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build storybook
          command: make storybook

      - persist_to_workspace:
          root: dist
          paths:
            - '*/storybook/'
  docs:
    docker:
      - image: circleci/node:12.10
    resource_class: xlarge

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website

      - persist_to_workspace:
          root: dist
          paths:
            - '*/docs/'

  docs-production:
    docker:
      - image: circleci/node:12.10
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website-production

      - persist_to_workspace:
          root: dist
          paths:
            - '*/docs/'

  deploy:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: |
            if [ $AZURE_STORAGE_SAS_TOKEN ]; then
              az storage blob upload-batch -d reactspectrum -s /tmp/dist --account-name reactspectrum
            fi

  deploy-production:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: az storage blob upload-batch -d "\$web" -s /tmp/dist/production/docs --account-name reactspectrum

  comment:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/react-spectrum
    steps:
      - checkout
      - restore_cache:
          key: rsp-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: comment on pr
          command: |
            if [ $GITHUB_TOKEN ]; then
              node .circleci/comment.js
            fi

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - storybook:
          requires:
            - build
      - docs:
          requires:
            - build
      - docs-production:
          filters:
            branches:
              only: main
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test
            - storybook
            - docs
      - deploy-production:
          filters:
            branches:
              only: main
          requires:
            - docs-production
      - comment:
          requires:
            - deploy
