name: 📝 Feedback
description: Have some feedback?
body:
  - type: markdown
    attributes:
      value: "### Thanks for filing an issue! Before you submit, search open/closed issues before submitting since someone might have asked the same thing before!"
  - type: markdown
    attributes:
      value: "# 📝 Feedback"
  - type: textarea
    attributes:
      label: Provide your feedback here.
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: 🔦 Context
      description: | 
        How has this issue affected you?
        What are you trying to accomplish?
  - type: textarea
    id: code-sample
    attributes:
      label: 💻 Code Sample
      description: If you have an example are seeing an error, please provide a code repository, gist or sample files to reproduce the issue
  - type: markdown
    attributes:
      value: "## 🌍 Your Environment"
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of react-spectrum are you running?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: other
    attributes:
      label: If other, please specify
  - type: input
    id: operating-system
    attributes:
      label: What operating system are you using?
