name: Manual nightly deploy
on: workflow_dispatch

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Run CircleCI
        id: nightly
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
