name: PR comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment workflow
    if: |
      github.event.issue.pull_request &&
      github.repository == 'adobe/react-spectrum' &&
      github.actor == 'LFDanLu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: yarn install
      - name: Comment contains trigger
        if: contains(github.event.comment.body, 'GET_BUILD')
        uses: ./.github/actions/branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
