name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node_version: 12.x
    - name: Write npmrc
      env:
        NPMRC: ${{ secrets.NPMRC }}
      run: echo "$NPMRC" > .npmrc
    - name: yarn install
      run: |
        make clean_node_modules
        make install_no_postinstall
    - name: build
      run: |
        make clean
        make -B
    - name: test
      run: make ci-test
    - name: build storybook
      run: make storybook
    - name: deploy storybook
      env:
        AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
      run: |
        az storage blob upload-batch -d reactspectrum -s storybook-static --account-name reactspectrum
    - name: comment on PR
      uses: actions/github@v1.0.0
      with:
        args: 'comment "Build successful! [View the storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/$(git rev-parse HEAD)/index.html)."'
